apiVersion: v1
kind: Namespace
metadata:
  name: k8si-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8si-operator
  namespace: k8si-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8si-operator
rules:
  - apiGroups: [k8si.io]
    resources: [k8sibackups, k8sibackups/status]
    verbs: [get, list, watch, patch, update]
  - apiGroups: [k8si.io]
    resources: [k8sibackupruns, k8sibackupruns/status]
    verbs: [get, list, watch, create, patch, update, delete]
  - apiGroups: [snapshot.storage.k8s.io]
    resources: [volumesnapshots]
    verbs: [create, get, list, watch, delete, patch, update]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [create, get, list, watch, delete]
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get, delete]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list]
  - apiGroups: [""]
    resources: [pods/exec]
    verbs: [create]
  - apiGroups: [""]
    resources: [pods/log]
    verbs: [get]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [create, get, list, watch, delete, patch, update]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8si-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8si-operator
subjects:
  - kind: ServiceAccount
    name: k8si-operator
    namespace: k8si-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8si-restore
rules:
  - apiGroups: [k8si.io]
    resources: [k8sibackups/status]
    verbs: [patch]
